from typing import Protocol

from src.app.domain.entities.event_message import EventMessage


class EventPublisherPort(Protocol):
    async def publish(self, event_message: EventMessage) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
