from typing import Optional, Protocol
from uuid import UUID

from src.app.domain.entities.user import CreateUserInput, UserEntity


class UserRepositoryPort(Protocol):
    async def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    async def get_by_username(self, username: str) -> Optional[UserEntity]: ...
    async def get_by_id(self, user_id: UUID) -> Optional[UserEntity]: ...
    async def create(self, input_data: CreateUserInput) -> UserEntity: ...
    async def update(self, user: UserEntity) -> UserEntity: ...
    async def delete(self, user_id: UUID) -> bool: ...
